//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CFRs.DAL {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class DALSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static DALSetting defaultInstance = ((DALSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DALSetting())));
        
        public static DALSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(DESCRIPTION =(ADDRESS_LIST =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.9." +
            "101.26)(PORT = 1521)))(CONNECT_DATA =(SID = lsncisdb)(SERVER = DEDICATED)));User" +
            " ID=ebao_ls_prod;Password=password;")]
        public string EBAOConnectionString {
            get {
                return ((string)(this["EBAOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SL-DEVFRDB01;Initial Catalog=LS_OSC_UOB;Persist Security Info=True;Us" +
            "er ID=LS_OSC_DEV;Password=3L89gBvqqV8DymCL")]
        public string OSCConnectionString {
            get {
                return ((string)(this["OSCConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SL-DEVFRDB01;Initial Catalog=CFRs;Persist Security Info=True;User ID=" +
            "CFR;Password=P@ssw0rd@123")]
        public string CFRsConnectionString {
            get {
                return ((string)(this["CFRsConnectionString"]));
            }
        }
    }
}
